GET http://localhost:8088/user/list

###

POST http://localhost:8088/user/register?username=jiang1&password=123

###

POST http://localhost:8088/disallowWord/add?value=lala

###

POST http://localhost:8088/disallowWord/delete?value=lala

###

GET http://localhost:8088/GetIP?date=2022-10-09

###

POST http://124.223.184.187:8088/AddUserWhiteIP?key=113.140.84.107

###

POST http://124.223.184.187:8088//DelUserWhiteIP?key=113.140.84.107

###
